services:
  - type: web
    name: wave-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -w 2 --threads 4 -b 0.0.0.0:$PORT server:app"
    envVars:
      - key: PATH
        value: /opt/render/ffmpeg:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - key: DOWNLOAD_DIR
        value: /tmp/downloads
      - key: STATIC_DIR
        value: ./static
      - key: FILE_TTL
        value: 600
      - key: JOB_TTL
        value: 1200
